[package]
name = "netload"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1.20.0", features = ["full"] }
clap = { version = "3.2.14", features = ["derive"] }
futures = "0.3"
colored = "2.0.0"
